### PR TITLE
MANT: update syntax for pyyaml > 3.13

### PR DESCRIPTION
**Pull request by chiahaoliu**
use `full_load` to avoid deprecation warning which will crash beamline machine

### CODE REVIEW

**Comment by CJ-Wright** [comment]
just a flake 8 error

**Comment by CJ-Wright** [comment]
The changes to the news stuff need to be matched in the rever file, since they are now rst files.

**Comment by chiahaoliu** [comment]
does 0e87ba9219a451537e38667dea1f48227b78d1f5 do it? Not sure what I am doing it correctly.

**Comment by CJ-Wright** [comment]
I think so, we can always backtrack the release of needed

**Comment by chiahaoliu** [comment]
@CJ-Wright could you help me take a look if this PR seems reasonable?

**Comment by CJ-Wright** [comment]
LGTM!

**Pull request merged**
